elasticsearch:
  container_name: elasticsearch
  restart: unless-stopped
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"

logstash:
  container_name: logstash
  restart: unless-stopped
  build: logstash/
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  ports:
    - "5000:5000"
    - "5044:5044"
  links:
    - elasticsearch
kibana:
  container_name: kibana
  restart: unless-stopped
  build: kibana/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
